version: "3.7" #https://docs.docker.com/compose/compose-file/compose-versioning/

#Docker Networks
# networks:
#   laravel_net_dev:
#     name: ${NETWORK_NAME_DEV}
#     ipam:
#       driver: default
#       config:
#         - subnet: ${NETWORK_IP_DEV}

networks:
  laravel_net_dev:
    name: ${NETWORK_NAME_DEV}

#Volumes
volumes:
  dbdata:
    name: "${PROJECT_PREFIX_DEV}_dbdata"
    driver: local

# Workflow
services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/dev/Dockerfile
    container_name: "${PROJECT_PREFIX_DEV}_nginx"
    ports:
      - ${EXTERNAl_IP_DEV}:80:80
      - ${EXTERNAl_IP_DEV}:443:443
      # - "80:80"
      # Port for xdebug (ensure this matches the remote_port in the xdebug.ini)
      #- "9001:9001"
    volumes:
      - ./www/ssuccessv2.com:/var/www/html:delegated
      - ./docker-logs/nginx:/var/log/nginx
      - ./compose/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./compose/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      NGINX_CONF_SERVER_NAMES_DEV: ${NGINX_CONF_SERVER_NAMES_DEV}
    depends_on:
      - php
      - mysql
    networks:
      - laravel_net_dev

  mysql:
    image: mysql:5.7.29 # Имя образа и его версия
    container_name: "${PROJECT_PREFIX_DEV}_mysql"
    restart: unless-stopped # Всегда перезапускайте контейнер, если он останавливается, за исключением того, что при остановке контейнера (вручную или иным образом) он не перезапускается даже после перезапуска демона Docker.always
    tty: true #подключает виртуальную консоль. Это нужно, чтобы команда cat не завершала работу, иначе контейнер остановится.
    expose:
      - 3306 # Порт контейнера
    environment: # Переменные из .env
      MYSQL_DATABASE: ${DB_DATABASE_DEV}
      MYSQL_USER: ${DB_USERNAME_DEV}
      MYSQL_PASSWORD: ${DB_PASSWORD_DEV}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD_DEV}
    volumes:
      #- ./compose/mysql/my.cnf:/etc/mysql/my.cnf # Конфиги
      - dbdata:/var/lib/mysql/ # Место где БД хранится, можно и локальный volume.
      - ./docker-logs/mysql:/var/log/mysql
    networks:
      - laravel_net_dev

  redis:
    image: "redis:alpine"
    container_name: "${PROJECT_PREFIX_DEV}_redis"
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - laravel_net_dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_PREFIX_DEV}_phpmyadmin"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD_DEV}
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - mysql
    ports:
    - "${EXTERNAl_IP_DEV}:8081:80"
    volumes:
      - /sessions
    networks:
      - laravel_net_dev
    links:
      - mysql

  php:
    build:
      context: .
      dockerfile: ./compose/php/Dockerfile
    container_name: "${PROJECT_PREFIX_DEV}_php"
    volumes:
      - ./www/ssuccessv2.com:/var/www/html:delegated # Каталог, где будет жить наш проект
      # Enable xdebug
      - ./compose/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      # Custom php.ini
      - ./compose/php/config/php.ini-dev:/usr/local/etc/php/php.ini
      # Error log
      - ./docker-logs/php/php_errors.log:/var/log/php_errors.log
      - ./docker-logs/php/fpm-php.www.log:/var/log/fpm-php.www.log
    expose:
      - 9000
    networks:
      - laravel_net_dev

  composer:
    build:
      context: .
      dockerfile: ./compose/php/composer/Dockerfile
    container_name: "${PROJECT_PREFIX_DEV}_composer"
    volumes:
      - ./www/ssuccessv2.com:/var/www/html # Каталог, где будет жить наш проект
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel_net_dev
    entrypoint: ['composer', '--ignore-platform-reqs']

  npm:
    image: node:15.0.1
    container_name: "${PROJECT_PREFIX_DEV}_npm"
    volumes:
      - ./www/ssuccessv2.com:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: ./compose/php/Dockerfile
    container_name: "${PROJECT_PREFIX_DEV}_artisan"
    volumes:
      - ./www/ssuccessv2.com:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel_net_dev
