version: "3.7" #https://docs.docker.com/compose/compose-file/compose-versioning/

#Docker Networks
# networks:
#   laravel_net_beta:
#     name: ${NETWORK_NAME_BETA}
#     ipam:
#       driver: default
#       config:
#         - subnet: ${NETWORK_IP_BETA}

networks:
  laravel_net_beta:
    name: ${NETWORK_NAME_BETA}

#Volumes
volumes:
  dbdata:
    name: "${PROJECT_PREFIX_BETA}_dbdata"
    driver: local

# Workflow
services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/beta/nginx/Dockerfile
    container_name: "${PROJECT_PREFIX_BETA}_nginx"
    ports:
      - ${EXTERNAl_IP_BETA}:80:80
      - ${EXTERNAl_IP_BETA}:443:443
    volumes:
      - ./www/ssuccessv2.com:/var/www/html:delegated
      - ./docker-logs/nginx:/var/log/nginx
      - ./compose/beta/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./compose/beta/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      NGINX_CONF_SERVER_NAMES_BETA: ${NGINX_CONF_SERVER_NAMES_BETA}
    depends_on:
      - php
      - mysql
    networks:
      - laravel_net_beta

  mysql:
    image: mysql:5.7.29 # Имя образа и его версия
    container_name: "${PROJECT_PREFIX_PROD}_mysql"
    restart: unless-stopped # Всегда перезапускайте контейнер, если он останавливается, за исключением того, что при остановке контейнера (вручную или иным образом) он не перезапускается даже после перезапуска демона Docker.always
    tty: true #подключает виртуальную консоль. Это нужно, чтобы команда cat не завершала работу, иначе контейнер остановится.
    expose:
      - 3306
    environment: # Переменные из .env
      MYSQL_DATABASE: ${DB_DATABASE_BETA}
      MYSQL_USER: ${DB_USERNAME_BETA}
      MYSQL_PASSWORD: ${DB_PASSWORD_BETA}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD_BETA}
    volumes:
      #- ./compose/beta/mysql/my.cnf:/etc/mysql/my.cnf # Конфиги
      - dbdata:/var/lib/mysql/ # Место где БД хранится, можно и локальный volume.
      - ./docker-logs/mysql:/var/log/mysql
    networks:
      - laravel_net_beta

  redis:
    image: "redis:alpine"
    container_name: "${PROJECT_PREFIX_BETA}_redis"
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - laravel_net_beta

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_PREFIX_BETA}_phpmyadmin"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - mysql
    ports:
    - "${EXTERNAl_IP_BETA}:8081:80"
    volumes:
      - /sessions
    networks:
      - laravel_net_beta
    links:
      - mysql

  php:
    build:
      context: .
      dockerfile: ./compose/beta/php/Dockerfile
    container_name: "${PROJECT_PREFIX_BETA}_php"
    volumes:
      - ./www/ssuccessv2.com:/var/www/html:delegated # Каталог, где будет жить наш проект
      # Custom php.ini
      - ./compose/beta/php/config/php.ini:/usr/local/etc/php/php.ini
      # Error log
      - ./docker-logs/php/php_errors.log:/var/log/php_errors.log
      - ./docker-logs/php/fpm-php.www.log:/var/log/fpm-php.www.log
    expose:
      - 9000
    networks:
      - laravel_net_beta

  composer:
    build:
      context: .
      dockerfile: ./compose/beta/php/composer/Dockerfile
    container_name: "${PROJECT_PREFIX_BETA}_composer"
    volumes:
      - ./www/ssuccessv2.com:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel_net_beta
    entrypoint: ['composer', '--ignore-platform-reqs']

  npm:
    image: node:15.0.1
    container_name: "${PROJECT_PREFIX_BETA}_npm"
    volumes:
      - ./www/ssuccessv2.com:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: ./compose/beta/php/Dockerfile
    container_name: "${PROJECT_PREFIX_BETA}_artisan"
    volumes:
      - ./www/ssuccessv2.com:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel_net_beta
